baseURL: "https://cbueno.github.io" 
title: Carlos Bueno
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Carlos Bueno research papers, curriculum vitae, and contact information."
    author: Carlos Bueno
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Carlos Bueno
          subtitle: "I am a PhD Researcher in Education Policy at the Autonomous University of Barcelona (UAB), funded by La Caixa INPhINIT Scholarship. My research focuses on geospatial approaches for educational planning, particularly related to school supply and school choice processes in order to enhance access to education and address school segregation issues in education systems. Previously I have worked across different UN organizations and NGOs on a variety of education topics, including curriculum reform and school dropout prevention." 
          imageUrl: "DSC02217_Caixa.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Outreach
              url: books/
            - name: CV
              url: courses/

    socialIcons:
        - name: CV
          url: CV_Carlos_Bueno.pdf
        - name: Email
          url: mailto:carlos.bueno.martinez@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=user
        - name: GitHub
          url: https://github.com/cbuenomar
        - name: Twitter
          url: https://x.com/charlie_good96

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
